<?xml version="1.0"?>
<package format="3">
  <name>pairs_precise_landing_gazebo</name>
  <version>2.0.0</version>
  <description>PAIRS precise landing Gazebo simulation resources (models, worlds)</description>
  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
    <gazebo_ros gazebo_model_path="${prefix}/share/pairs_precise_landing_gazebo/models"/>
  </export>
</package>
