<?xml version="1.0"?>
<package format="2">

  <name>pairs_precise_landing</name>
  <version>1.0.0</version>
  <description>pairs_precise_landing</description>

  <maintainer email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</maintainer>
  <author email="canhthanh@vnu.edu.vn">Thanh Nguyen Canh</author>

  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>cmake_modules</depend>
  <depend>roscpp</depend>
  <depend>geometry_msgs</depend>
  <depend>pairs_lib</depend>
  <depend>nodelet</depend>
  <depend>pairs_msgs</depend>
  <depend>pairs_landing_pad_estimation</depend>

  <export>
    <nodelet plugin="${prefix}/nodelets.xml" />
  </export>

</package>
